gemotes.EmoteCooldown = 0.5

gemotes.RegisterEmote("gemotes/wapp/hi.png", "gemotes/wapp/hi.ogg")
gemotes.RegisterEmote("gemotes/wapp/bye.png", "gemotes/wapp/bye.ogg")
gemotes.RegisterEmote("gemotes/wapp/happy.png", "gemotes/wapp/happy.ogg")
gemotes.RegisterEmote("gemotes/wapp/sob.png", "gemotes/wapp/sob.ogg")
gemotes.RegisterEmote("gemotes/wapp/rofl.png", "gemotes/wapp/rofl.ogg")
gemotes.RegisterEmote("gemotes/wapp/think.png", "gemotes/wapp/think.ogg")
gemotes.RegisterEmote("gemotes/wapp/scream.png", "gemotes/wapp/scream.ogg")
gemotes.RegisterEmote("gemotes/wapp/wow.png", "gemotes/wapp/wow.ogg")
gemotes.RegisterEmote("gemotes/wapp/rage.png", "gemotes/wapp/rage.ogg")
gemotes.RegisterEmote("gemotes/wapp/huh.png", "gemotes/wapp/huh.ogg")
gemotes.RegisterEmote("gemotes/wapp/sleep.png", "gemotes/wapp/sleep.ogg")
gemotes.RegisterEmote("gemotes/wapp/clap.png", "gemotes/wapp/clap.ogg")
gemotes.RegisterEmote("gemotes/wapp/vomit.png", "gemotes/wapp/vomit.ogg")
gemotes.RegisterEmote("gemotes/wapp/evil.png", "gemotes/wapp/evil.ogg")
gemotes.RegisterEmote("gemotes/wapp/shock.png", "gemotes/wapp/shock.ogg")
gemotes.RegisterEmote("gemotes/wapp/yawn.png", "gemotes/wapp/yawn.ogg")