-- gemotions.RegisterEmote(page, image, sound)

gemotions.RegisterEmote("wapp", "gemotions/wapp/hi.png", "gemotions/wapp/hi.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/bye.png", "gemotions/wapp/bye.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/happy.png", "gemotions/wapp/happy.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/sob.png", "gemotions/wapp/sob.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/rofl.png", "gemotions/wapp/rofl.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/think.png", "gemotions/wapp/think.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/scream.png", "gemotions/wapp/scream.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/wow.png", "gemotions/wapp/wow.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/rage.png", "gemotions/wapp/rage.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/huh.png", "gemotions/wapp/huh.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/sleep.png", "gemotions/wapp/sleep.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/clap.png", "gemotions/wapp/clap.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/vomit.png", "gemotions/wapp/vomit.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/evil.png", "gemotions/wapp/evil.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/shock.png", "gemotions/wapp/shock.ogg")
gemotions.RegisterEmote("wapp", "gemotions/wapp/yawn.png", "gemotions/wapp/yawn.ogg")