
gemotions.RegisterPackage("main", "Emotions", {
    {"gemotions/main/hi.png", "gemotions/main/hi.ogg"},
    {"gemotions/main/bye.png", "gemotions/main/bye.ogg"},
    {"gemotions/main/happy.png", "gemotions/main/happy.ogg"},
    {"gemotions/main/sob.png", "gemotions/main/sob.ogg"},
    {"gemotions/main/rofl.png", "gemotions/main/rofl.ogg"},
    {"gemotions/main/think.png", "gemotions/main/think.ogg"},
    {"gemotions/main/scream.png", "gemotions/main/scream.ogg"},
    {"gemotions/main/wow.png", "gemotions/main/wow.ogg"},
    {"gemotions/main/rage.png", "gemotions/main/rage.ogg"},
    {"gemotions/main/huh.png", "gemotions/main/huh.ogg"},
    {"gemotions/main/sleep.png", "gemotions/main/sleep.ogg"},
    {"gemotions/main/clap.png", "gemotions/main/clap.ogg"},
    {"gemotions/main/vomit.png", "gemotions/main/vomit.ogg"},
    {"gemotions/main/evil.png", "gemotions/main/evil.ogg"},
    {"gemotions/main/shock.png", "gemotions/main/shock.ogg"},
    {"gemotions/main/yawn.png", "gemotions/main/yawn.ogg"},
    {"gemotions/main/nerd.png", "gemotions/main/nerd.ogg"},
})